# Site settings

remote_theme : mkchoi212/paper-jekyll-theme

title: "ExLL: an extremely low-latency congestion control for mobile cellular networks"
description: > 
  @ [Mobile System & Networking Lab , UNIST](https://msn.unist.ac.kr)
author: MSNL
email: sipark@unist.ac.kr
github_username: shinikpark

baseurl: "/exll" # the subpath of your site, e.g. /blog
url: "https://msnl.github.io" # the base hostname & protocol for your site

google_analytics_id: 
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]
